### ISSUE TITLE
Some suggestions on the input checking steps.

### ISSUE THREAD

**Issue by YADengUU** [ttsse/Hes1_tissue_parameters#2]
It could also be applied to the other function without parallelization, if the modifications make sense. It might be helpful to check if there are enough inputs before checking if the array/matrix/vector is empty. It could be more organized to check each input in turns. In addition to non-positive inputs, non-numeric entries sometimes happen accidentally and they are also spurious. I ran into similar problems during my own project, hope these suggestions could help.
% check that input is in the right format
% first need to be sure there are enough inputs
if nargin < 3
    % use your suitable error id here
    error('MyError:InadequateInput','Not enough inputs');      
end

% then check if the inputs have empty entries
%  before checking if they are nonsense
if isempty(D_d)
    error('MATLAB:notEnoughInputs', 'D_d cannot be empty.');
elseif ~isnumeric(D_d) % also need to make sure they have numeric entries
    % use your suitable error id here
    error('MyError:nonNumericInputs', 'D_d entries must be numeric.');
elseif D_d<=0
    error('MathBiology:negativeParameters', 'D_d needs to be positive.');
end

if isempty(h)
    error('MATLAB:notEnoughInputs', 'h cannot be empty.');
elseif ~isnumeric(h)
    % use your suitable error id here
    error('MyError:nonNumericInputs', 'h must be numeric.');
elseif h<=0
    error('MathBiology:negativeParameters', 'h needs to be positive.');
end 

if isempty(gamma)
    error('MATLAB:notEnoughInputs', 'gamma cannot be empty');
elseif ~isnumeric(gamma)
    % use your suitable error id here
    error('MyError:nonNumericInputs', 'gamma must be numeric.');
elseif gamma<=0
    error('MathBiology:negativeParameters', 'gamma needs to be positive.');
end

**Comment by menzge** [comment]
Fixed with pull request from YADengUU
